### ISSUE TITLE
opencv-python下载问题

### ISSUE THREAD

**Issue by lyw321** [HDUMIL/summer-school#10]
我用命令行pip install opencv-python ，  显示requirement already satisfied.... IDLE里import cv2没有报错，但是notebook里报错了，请问如何解决

**Comment by 0xMashiro** [comment]
因为 Windows 平台下的环境配置需要十分谨慎，你需要确认是否将 `opencv-python` 安装到了自己使用的 `conda`  环境，检查当前已安装库的命令是：

```python
$(base) conda list
```
如果你在列表中没有找到 `opencv-python` , 则无法在 notebook 中 `import cv2`.

有一种情况是你在 Cmd / Powershell 和 集成开发环境中使用的 Python (系统环境变量 `PYTHONPATH`) 是一个环境，
而在 Anaconda 中使用的 Python 又是另一个环境... 建议在 Anaconda Prompt 中执行对应的 `pip install` 指令.

由于不知道你是在哪个命令行窗口执行的安装，可能还是要用前面的 `conda list` 具体检查一下是否安装到位了，
这种情况特别容易发生在以前安装过类似环境的机器上面，所以 `conda` 一般都针对不同的任务使用不同的虚拟环境。

**Comment by shaonianruntu** [comment]
# Windows 平台下 Python 安装 opencv 的方法

进入 https://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv ，根据之前python的版本决定下载whl格式文件，下载后进入文件所在位置，命令行输入pip install *.whl

![image](https://user-images.githubusercontent.com/16336682/60660854-406c6880-9e8b-11e9-975d-3f68d38a8a98.png)

参考链接：https://blog.csdn.net/LYJ_viviani/article/details/59482602

**Comment by 0xMashiro** [comment]
> # Windows 平台下 Python 安装 opencv 的方法
> 进入 https://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv ，根据之前python的版本决定下载whl格式文件，下载后进入文件所在位置，命令行输入pip install *.whl
> 
> ![image](https://user-images.githubusercontent.com/16336682/60660854-406c6880-9e8b-11e9-975d-3f68d38a8a98.png)
> 
> 参考链接：https://blog.csdn.net/LYJ_viviani/article/details/59482602

对的，这个方法也可以解决 `pip` 依旧下载速度慢的问题，原来的 `pip install` 默认是从源端服务器下载到本地安装的，如果它在本地检测到路径下有这个 whl 文件，就会直接进行安装。你现在成功安装上 `opencv-python` 了吗？可以用 `conda list` 指令检查一下。

**Comment by lyw321** [comment]
我在用anaconda prompt下载 我说怎么这么慢... 才到40%  pip list行吗  conda list我不会...

**Comment by 0xMashiro** [comment]
> 我在用anaconda prompt下载 我说怎么这么慢... 才到40% pip list行吗 conda list我不会...

打开 Anaconda Prompt 后直接输入 `conda list` 后回车就可以看当前安装的所有库了，谷歌一下 “conda 常用命令” ~

`conda` 其实就是一个包管理器啦，就好像前端的 `npm`, 不过也 `conda` 兼容 `pip`, 毕竟很多的包在 `conda` 维护的仓库中没有。

**Comment by lyw321** [comment]
> > 我在用anaconda prompt下载 我说怎么这么慢... 才到40% pip list行吗 conda list我不会...
> 
> 打开 Anaconda Prompt 后直接输入 `conda list` 后回车就可以看当前安装的所有库了，谷歌一下 “conda 常用命令” ~
> 
> `conda` 其实就是一个包管理器啦，就好像前端的 `npm`, 不过也 `conda` 兼容 `pip`, 毕竟很多的包在 `conda` 维护的仓库中没有。

我现在import cv2不会报错了，但是conda list里面没有cv2... 而且我逐条执行
`IMG_URL = "E:/360data/重要数据/桌面/zm.jpg"
img = cv2.imread(IMG_URL)
print(img.size)
print(img.shape)
plt.imshow(img)`
前2条正常执行()，后面就报错了,报错信息是
`AttributeError                            Traceback (most recent call last)
<ipython-input-5-3320932b5ca9> in <module>()
----> 1 print(img.size)

AttributeError: 'NoneType' object has no attribute 'size'
`

**Comment by 0xMashiro** [comment]
> > > 我在用anaconda prompt下载 我说怎么这么慢... 才到40% pip list行吗 conda list我不会...
> > 
> > 
> > 打开 Anaconda Prompt 后直接输入 `conda list` 后回车就可以看当前安装的所有库了，谷歌一下 “conda 常用命令” ~
> > `conda` 其实就是一个包管理器啦，就好像前端的 `npm`, 不过也 `conda` 兼容 `pip`, 毕竟很多的包在 `conda` 维护的仓库中没有。
> 
> 我现在import cv2不会报错了，但是conda list里面没有cv2... 而且我逐条执行
> `IMG_URL = "E:/360data/重要数据/桌面/zm.jpg" img = cv2.imread(IMG_URL) print(img.size) print(img.shape) plt.imshow(img)`
> 前2条正常执行()，后面就报错了,报错信息是
> `AttributeError Traceback (most recent call last)
> in ()
> ----> 1 print(img.size)
> 
> AttributeError: 'NoneType' object has no attribute 'size'
> `

```python
import cv2
```

导入成功就没问题了，`conda list` 中显示的应该是 `opencv-python`, `cv2` 是使用时的别名(历史更新原因).

你的 Markdown 语法使用不对，可以查一下标准语法如何使用。

```python
IMG_URL = "E:/360data/重要数据/桌面/zm.jpg" 
img = cv2.imread(IMG_URL) 
print(img.size) 
print(img.shape) 
plt.imshow(img)
```

```
'NoneType' object has no attribute 'size'
```

出现这样的报错一般建议直接谷歌报错的语句，网络上会有很多参考。

![Screenshot_1](https://user-images.githubusercontent.com/21091736/60669769-b5e33380-9ea1-11e9-8f28-c1163208c5e4.png)

在《提问的智慧》中有提到如何自己去分析和解决问题，需要慢慢地学会如何独立处理报错，甚至是连续报错。

------

建议先检查一下代码是否完全一致，因为如果是因为代码写错了，就无法分析了：

```python
import cv2
import numpy as np
import matplotlib.pyplot as plt

IMG_URL = "lenna.jpg"               # 换成你的图片路径
img = cv2.imread(IMG_URL)       # OpenCV 默认读入 BGR 格式
img_RGB = img[:,:,::-1]                # 转不转 RGB 格式其实无所谓
plt.imshow(img_RGB)
print(img_RGB.size)
print(img_RGB.shape)
```

那么造成你实际问题的原因是什么呢？

**写代码的时候不要有中文路径。**

是的，你的图片并没有没成功地读进去...
