### ISSUE TITLE
梯度下降细节

### ISSUE THREAD

**Issue by wtSerious** [HDUMIL/summer-school#11]
在线性模型系列-2中，原文有一段这样的描述：
问题变成了在红色圆圈范围内找出向量 $(\Delta \theta_1, \Delta \theta_2)$, 使之与 $(u, v)$ 的内积最小。显然此时 $(\Delta \theta_1, \Delta \theta_2)$ 的方向应该与 $(u, v)$ 相反，大小应当等于圆圈半径 $d$, 用 $\eta$ 表示半径即
$\left[ \begin{array}{c} {\Delta \theta_{1}} \\ {\Delta \theta_{2}}\end{array}\right] =-\eta \left[ \begin{array}{}{u} \\ {v}\end{array}\right]=\left[ \begin{array}{c}{\theta_{1}-a} \\ {\theta_{1}-b} \end{array}\right]$
我对用 $\eta$ 表示半径 这一说法有些不解。
应设 $(\Delta \theta_{1},\Delta \theta_{2})$ = $-a$$(u,v)$，为使内积最小，$(\Delta \theta_{1},\Delta \theta_{2})$的长度应为 $d$，那么 $a^{2}$$($$\Delta \theta_{1} ^{2}+\Delta \theta_{2}^{2}）= d^{2}$
$a$ = $d/ (\Delta \theta_{1}^{2}+\Delta \theta_{2}^{2})^{1/2}$。应使 $\eta$=$a$，此时才能保证是在长度半径为 $d$ 的圆内寻找一个最小值。
同时也较符合前面在 Adagrad 中，寻找一个合适的 $\eta$ 需要除以梯度的均方根，但此时又有一个疑问，最合适的 $\eta$ 只需要除以当前位置梯度的均方根，而Adam中则是需要除以之前所有梯度的均方根，哪个比较合理呢？
设定一个小的 $d$，然后通过计算使 $\eta$ = $a$，进行训练是否合理(原本需要考虑的使学习率，而现在我们需要考虑的是 $d$ 的大小)

**Comment by 0xMashiro** [comment]
这里引入的 $\eta$ 其实只是为了对“半径”这个概念进行单纯数学符号上的替换，因为在机器学习中学习率通常使用 $\eta$ 来表示，符合常用的数学表示(也有可能是其它符号), 但是一般不会直接用 $d$ 来表示所有参数的更新(毕竟有很多的参数，单纯用两个参数的情况来表示不太准确).  这一小节的用意是使用”在圆圈内找一个点“的形式来类比梯度下降的一次参数更新过程，而实际上呢这个“半径”是很难精确定义的，在前面也讨论了如何制定合适的“半径”，即学习率作用在梯度上的结果。我的博文表述有问题，导致容易把读者的想法带歪，待会儿去修改一下表述。至于你最后的那句话，其实设定一个小的 $d$  其实就是在设定参数更新的上界了，我会把 ”用 $\eta$ 表示半径” 改为 “用 $\eta$ 和 $(u,v)$ 表示实际的更新幅度”, 这样的话能理解了吗？

至于学习率的寻找，一直也是机器学习的研究方向，也有很多相关的论文，adam 是比较主流的方法，实际上在一些较新的论文中，对 adam 进行了改进，出于篇幅原因没有更新进去，但是大家只要知道就算是超参数，也是值得研究的啦。

**Comment by 0xMashiro** [comment]
博文增加了一些相关的表示，还是得再夸夸你对 Adagrad 的思考，因为科研也是在思考不同方法之间的差异，通过实验等形式进行方法理论上的证明与创新。如果没有其它的疑惑了，你可以关闭掉这个 Issue.
