### ISSUE TITLE
Image包里的convert函数图像转换为灰度图 ，结果显示颜色错误

### ISSUE THREAD

**Issue by hwZhang98** [HDUMIL/summer-school#8]
完整代码如下：
```
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
IMG_URL = "lenna.jpg"   # 这个图片需要单独下载，或者你自己选用图片
img = Image.open(IMG_URL)
print(img.getpixel((0, 0)))
print('img mode',img.mode)                       # 显示图像的颜色格式 -- RGB
img_1 = img.convert('L')                             # 转化图像模式，L为灰度图
print('gray mode', img_1.mode)                  
print(img_1.getpixel((0, 0)))
plt.imshow(img_1)                                       # 更改部分
plt.show()
```
上述代码为所给材料里面的，结果输出图像为下：
![1](https://user-images.githubusercontent.com/46925115/60635930-15f8bc00-9e47-11e9-9e56-b7030752a25b.png)
而当把上面更改行代码改为
`plt.imshow(img_1,cmap='gray')`
此时输出为下
![2](https://user-images.githubusercontent.com/46925115/60635985-48a2b480-9e47-11e9-8396-6212c2dd3b99.png)
此时结果正确
可是在有些电脑上并不需要进行这种修改，直接显示的就是正常的灰度图，查阅过convert的文档，里面也只是说了convert的几种模式，包括黑白‘1’，灰度‘L’等，而去查阅imshow中的cmap参数时，上面解释为cmap: 颜色图谱（colormap), 默认绘制为RGB(A)颜色空间。而cmap='gray'指的是 gray | 黑-白空间，所以就产生了上面第二个结果，可是当我更改convert模式为‘1’时，按理说此时应该显示为黑白图，可是结果却如下所示：
![3](https://user-images.githubusercontent.com/46925115/60636223-337a5580-9e48-11e9-8964-30d040d7f640.png)
接着像原来一样更改更改部分的代码后，就输出了正确的结果：
![4](https://user-images.githubusercontent.com/46925115/60636245-4a20ac80-9e48-11e9-8ef6-0a32bc46cab9.png)
我在想是因为颜色空间为黑白，限制了原先输出的错误图像，把绿色变为黑白，把黄色变为黑白。从而导致输出的是正确的结果，但当我把图换成了没有经过convert转换的原图时：
![111](https://user-images.githubusercontent.com/46925115/60636414-f2367580-9e48-11e9-81ac-11b895b8ed9c.png)
此时我仍然修改那句代码：
plt.imshow(img_1,cmap='gray'）
可是输出的图像却一点变化也没有
问题1：为什么原图没有经过convert的转化，就不会受到cmap参数的影响，变为黑白，
问题2：为什么同样的代码，经过version输出的灰度图是绿色的，模式1是黄色的

**Comment by 0xMashiro** [comment]
已经看见你的问题，下午研究一下。

**Comment by hwZhang98** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "Xiao-Wei CAO"<notifications@github.com>; 
发送时间: 2019年7月4日(星期四) 中午11:05
收件人: "HDUMIL/summer-school"<summer-school@noreply.github.com>; 
抄送: "张昊文"<654181472@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [HDUMIL/summer-school] Image包里的convert函数图像转换为灰度图 ，结果显示颜色错误 (#8)




已经看见你的问题，下午研究一下。

**Comment by 0xMashiro** [comment]
@Zhanghaowen98  有的时候查文档可能不足以解决问题，还需要查看源码，其实在教程的下面提到了 `plt.imshow()` 和 `plt.show()` 的区别，PIL 的图像格式并不是 Numpy 数组格式，你可以先跑完整个笔记本，看看是否能解答自己的疑惑。

**Comment by hwZhang98** [comment]
好的，谢谢助教




------------------ 原始邮件 ------------------
发件人: "Xiao-Wei CAO"<notifications@github.com>; 
发送时间: 2019年7月4日(星期四) 中午11:24
收件人: "HDUMIL/summer-school"<summer-school@noreply.github.com>; 
抄送: "张昊文"<654181472@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [HDUMIL/summer-school] Image包里的convert函数图像转换为灰度图 ，结果显示颜色错误 (#8)




@Zhanghaowen98  有的时候查文档可能不足以解决问题，还需要查看源码，其实在教程的下面提到了 plt.imgshow() 和 plt.show() 的区别，PIL 的图像格式并不是 Numpy 数组格式，你可以先跑完整个笔记本，看看是否能解答自己的疑惑。

**Comment by 0xMashiro** [comment]
@Zhanghaowen98 使用你的代码，我无法在我的机器上复现你的问题，建议你将 `print()` 的结果也发上来。

一个可能有效的解决方式是在使用 `open()` 函数的同时加上 `convert('RGB')`, 即使用：

```python
img = Image.open(IMG_URL).convert('RGB')
```

你可以参考[这篇博客](https://blog.csdn.net/Jason160918/article/details/89605632)，情况和你类似，从而分析出背后的原因。

可能的一种原因是，在 `open()` 时误认为像素矩阵是二维的，默认打开的是灰度图格式（“L”），博客中利用 `np.array()` 函数将其转化为数组的形式，然后发现像素值是属于 `[0, 255]` 范围，所以造成图像失真。但是实际上我用下列代码测试的效果和你的不同：

```python
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

IMG_URL = "lenna.jpg"
img = Image.open(IMG_URL).convert('RGB')
plt.imshow(np.array(img.convert('L')) * 255)
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/21091736/60641819-1d788f00-9e60-11e9-9aec-ac24bdd5cb6e.png)

第二种可能的原因是读入的时候是以 `BGR` 顺序读入的(为什么会这样呢，可能还是要复现了才知道)：

```python
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

IMG_URL = "lenna.jpg"
img = Image.open(IMG_URL).convert('RGB')
plt.imshow(np.array(img)[:,:,-1])
plt.show()
```

![Figure_2](https://user-images.githubusercontent.com/21091736/60641939-9d065e00-9e60-11e9-95a9-e956145661ac.png)

看到这儿，我相信你已经知道了答案，光看文档的思考深度不足以解决问题，搜索博客也是一种技巧，
读源码能够让你想到用 Numpy 数组的形式显示图片，毕竟 PIL 图片封装得太高级，不利于了解底层。

有兴趣的话，也可以利用切片的技巧修改 Numpy 数组中的像素值，这样也可以加深理解~
其实如果你在跑完所有的笔记本代码后，再思考这个现象，会更快地得到答案，所以提问之前的处理也是一种艺术。


---------------

注：这个回答并不够清楚且存在错误语法，请关注后续提问与回答 #9
