### ISSUE TITLE
关于PIL显示图片颜色失真问题 后续

### ISSUE THREAD

**Issue by hwZhang98** [HDUMIL/summer-school#9]
在看过助教给的博客和可能BUG分析后，我又专门的进行了尝试，首先全部代码如下：
`from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

IMG_URL = "lenna.jpg"
img = Image.open(IMG_URL)
print('img mode'+str(img.mode))
img_np = np.array(img)
plt.subplot(1,2,1)
plt.imshow(img)
print('img size'+str(img.size))
print('img_np shape'+str(img_np.shape))
print('img_np size'+str(img_np.size))

img_1 = img.convert('L')
img_1_np = np.array(img_1)
print('img_1 mode'+str(img_1.mode))
plt.subplot(1,2,2)
plt.imshow(img_1)
print('img_1 size'+str(img_1.size))
print('img_1_np shape'+str(img_1_np.shape))
print('img_1_np size'+str(img_1_np.size))
print('Value range from ' + str(img_1_np.min()) + ' to ' + str(img_1_np.max()))
plt.show()
print(img_1_np)
#下面为分离通道测试------------------------------------------------------------------------分割线

img_r, img_g, img_b = img.convert('RGB').split()

plt.figure(figsize=(10,10))                    # 调整子图大小
plt.subplots_adjust(wspace =0.5, hspace =0.5)  # 调整子图间距

plt.subplot(2,3,1)
plt.imshow(img_r)  # 红色 Red
plt.xlabel('red channel')

plt.subplot(2,3,2)
plt.imshow(img_g)  # 绿色 Green
plt.xlabel('green channel')

plt.subplot(2,3,3)
plt.imshow(img_b)  # 蓝色 Blue
plt.xlabel('blue channel')

plt.subplot(2,3,4)
plt.imshow(img_np[:, :, 0])  # 红色 Red
plt.xlabel('red channel2')

plt.subplot(2,3,5)
plt.imshow(img_np[:, :, 1])  # 绿色 Green
plt.xlabel('green channel2')

plt.subplot(2,3,6)
plt.imshow(img_np[:, :, 2])  # 蓝色 Blue
plt.xlabel('blue channel2')

plt.show()`
博客指出问题可能是以下两种情况
1.第一种是用open打开函数后，图片为错误的两维图片而不是三维，会将强制性把图片认为是灰度图格式。运行一次代码，结果如下：

![QQ图片20190704160525](https://user-images.githubusercontent.com/46925115/60649897-93d3bc00-9e75-11e9-8d7d-fa24885aad08.png)

![R(@HA%% 3OKF1 GH0%1F$XR](https://user-images.githubusercontent.com/46925115/60648608-d34cd900-9e72-11e9-92df-ff72d0340a7b.png)
可以看到，图片转化为矩阵后的维度没有问题，是三维的，并且mode也为RGB模式，所以第一种情况排除。
2.第二种是如果是三维的图片，可能打开的图片错误的用BGR格式打开，此时需要转化为RGB，我用博客上的方法进行转化后，结果如下：
![K{XSUZG J(~QDDFUO 0352](https://user-images.githubusercontent.com/46925115/60648976-a816b980-9e73-11e9-906f-5b45e6b9bc6e.png)
可以看到输入的原图因为格式的原因发生了变化，所以说明输入的本来就是RGB格式，第二种情况也排除。
接下来我又进行了思考和分析，首先进行convert转化为灰度模式后，img_1的模式确实是‘L’，说明确实是灰度模式，接着我发现这个图和应该正常的结果像素大小范围也是一样的，并且矩阵中每一个元素都一样。。。也就是模式一样都是L，矩阵元素也都一样，可是显示出来却不对，对比如下：
![O_ZYIFH06JT~HK~G~PSBLQ6](https://user-images.githubusercontent.com/46925115/60649289-51f64600-9e74-11e9-93c0-4aca622d7e1a.png)
![$8UT_)BHUXSV@3LWNY7NGX1](https://user-images.githubusercontent.com/46925115/60649292-528edc80-9e74-11e9-87a0-8d006d571aae.png)
接下来我又分离三通道，也就是分割线之下的代码，发现了和示例不一样的地方，文档说用手动分离和用函数分离得到的单通道图不一样，可是我的经过分离之后，两种情况却一样。。。。无语了。。下图是示例结果，接着是我的结果：
![}C19NG%YC@CT27)BHD)AMVF](https://user-images.githubusercontent.com/46925115/60649611-e95b9900-9e74-11e9-8822-327c39e177ff.png)
![)_92OV(EC06(DZWNMQMI5(F](https://user-images.githubusercontent.com/46925115/60649642-f6788800-9e74-11e9-8e8c-4997d3360473.png)
![49(XY$YX6KHJ3PLDS)X)UEW](https://user-images.githubusercontent.com/46925115/60649677-0a23ee80-9e75-11e9-8320-c4c0090c7e44.png)
我觉得已经超出我能力范围了，因为确实一些函数文档全英我看的很吃力，只能看懂一部分，而且明明模式一样，每个像素矩阵也一样，为什么显示就不一样

**Comment by 0xMashiro** [comment]
在前面的回答 #8  中，我疏忽了语法问题，Numpy 数组 RGB 转 BGR 应该是：

```python
IMG_URL = "lenna.jpg"
img = Image.open(IMG_URL).convert('RGB')
plt.imshow(np.array(img)[:,:,::-1])
plt.show()
```

我之前给出的 `plt.imshow(np.array(img)[:,:,-1])` 作用是显示索引为 `-1` 的通道，即绿色通道。

---------

回到这个问题，先看一个我机器上的对比例程：

```python
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

img = Image.open('lenna.jpg')
img = np.array(img)
if img.ndim == 3:
    img = img[:,:,1]
plt.subplot(221); plt.imshow(img)
plt.subplot(222); plt.imshow(img, cmap ='gray')
plt.subplot(223); plt.imshow(img, cmap = plt.cm.gray)
plt.subplot(224); plt.imshow(img, cmap = plt.cm.gray_r)
plt.show()
```

![download](https://user-images.githubusercontent.com/21091736/60661229-1f584780-9e8c-11e9-9629-3eb59b3e1d95.png)

我想你现在已经知道理想输出的情况是什么了，而且分析了这么多，我们可以认为 `plt.imshow()` 这个函数在你的机器上没有体现出差异。

- PIL 格式的三通道图片，调用 `split()` 分离出三通道后，得到的是 3 个单通道的 PIL 图片对象
- 而我们用 Numpy 数组转换 RGB  图，得到的已经是 Numpy 数组对象，认为分离后得到的是 3 个二维的 Numpy 数组(矩阵)

`plt.imshow()` 对于 PIL 和 Numpy 的显示机制不一样，用代码来显示这个差异就是：

```python
IMG_URL = "lenna.jpg"
img = Image.open(IMG_URL).convert('RGB')

plt.subplot(1,2,1)
plt.imshow(img.split()[1])        # PIL (without cmap setting)

plt.subplot(1,2,2)
plt.imshow(np.array(img)[:,:,1])  # numpy

plt.show()
```

![download](https://user-images.githubusercontent.com/21091736/60660309-0fd7ff00-9e8a-11e9-8c8a-a3fc7628f8ff.png)

如果我对你的问题理解没有出错，你运行上面这段代码，可能会得到效果相同的图片 : (  就像下面这样

![download](https://user-images.githubusercontent.com/21091736/60660821-292d7b00-9e8b-11e9-83d8-125d9989e30b.png)

而通过观察 Numpy 数组我们排除了 `convert('L')` 的嫌疑

所以问题是 `imshow.()` 对于单通道的 PIL 图片没有按照默认的灰度图方式去显示...

这个问题在其他人的机器上能复现吗？因为产生这样的情况的原因不好分析了，**只能用 `cmap='gray'` 临时纠正这种问题。**

如果的确是 `matplotlib` 不能够很好地显示图片，你可以使用 `PIL` 自带的显示方式看看效果：

```python
img = Image.open(IMG_URL, 'r').convert('L')
img.show()     # 不用带参数
```

我们只能猜测 WTF , `matplotlib` 的 `imshow()` 不够智能，在我机器上的 `matplotlib` 是 3.0.2 版本，一切都是正常的。

不要因为这个地方的一些小 BUG 打击自信心，你已经做得相当好了！

**Comment by hwZhang98** [comment]
谢谢助教，自己去钻研也确实搞明白很多东西

**Comment by 0xMashiro** [comment]
我现在在想的是，是不是由于 `plt.imshow()` 的默认显示方式设置出现了问题，你尝试运行下面这个代码：

```python
import matplotlib.pyplot as plt
plt.gray()
```

官方文档[在这里](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.gray.html) , 我帮你大概翻译一下：

将 `colormap` 设置为 “gray” - 这会更改默认的 `colormap` 以及当前图像的 `colormap` (如果有的话).

它的源码也很简单：

```python
def gray():
    """
    Set the colormap to "gray".

    This changes the default colormap as well as the colormap of the current
    image if there is one. See ``help(colormaps)`` for more information.
    """
    set_cmap("gray")
```

如果的确是这个原因，这将一劳永逸地解决你的问题。
这也说明可能你在 python 练习笔记本中玩 `matplotlib` 的时候对默认的参数不小心进行了改动。

**Comment by hwZhang98** [comment]
可以了，加上这句代码后，结果正常了，但是imshow()依然没有在我的机器上体现出差异，convert可以正常使用了，结果如下
![}T$_{ R`9`D_YC}WEP_RQMU](https://user-images.githubusercontent.com/46925115/60662799-f5a11f80-9e8f-11e9-8373-7732219f9c84.png)

![EKF5Z4@K2VLJZ%Q(B5}6BE](https://user-images.githubusercontent.com/46925115/60662783-e6ba6d00-9e8f-11e9-98fb-eb681513ebff.png)

**Comment by 0xMashiro** [comment]
行，先这样处理吧，周五的时候线下再看看。:blush:
